
spring.profiles.active: local


#server: 
#  servlet.contextPath: /sp
#  ssl: 
#    enabled: true
#    key-alias: tomcat
#    key-store-password: abc123
#    key-store: classpath:keystore.p12
#    key-store-type: PKCS12

spring: 
  application: 
    name: testspringboot213


---
#本地开发环境:local-----------------------------------------------------------------------------------------------------------
spring.profiles: local
server.port: 10000
#eureka: 
#  client: 
#    registerWithEureka: true
#    fetchRegistry: true
#    serviceUrl: 
#      defaultZone: http://127.0.0.1:10000/eureka/
#  instance:
#    instance-id: 127.0.0.1:SSO:10001
#    preferIpAddress: true
    


